---
env:
    es6: true
    node: true
extends:
    - eslint:recommended
    - plugin:import/errors
    - plugin:import/warnings
    - plugin:json/recommended
plugins:
    - import
    - node
parser: "@babel/eslint-parser"
parserOptions:
    sourceType: module
    ecmaVersion: 2020
rules:
    indent:
        - error
        - 4
    linebreak-style:
        - error
        - unix
    quotes:
        - error
        - double
    semi:
        - error
        - never
    array-bracket-spacing:
        - error
        - always
        -   singleValue: false
            arraysInArrays: false
            objectsInArrays: false
    array-bracket-newline:
        - error
        -   multiline: true
    array-element-newline:
        - error
        -   multiline: true
    block-spacing: error
    brace-style:
        - error
        - 1tbs
        -   allowSingleLine: true
    comma-dangle:
        - error
        - never
    comma-spacing:
        - error
        -   before: false
            after: true
    comma-style:
        - error
        - last
    computed-property-spacing:
        - error
        - never
        -   enforceForClassMembers: true
    constructor-super: error
    curly:
        - error
        - multi
    default-case: error
    default-case-last: error
    default-param-last:
        - error
    dot-notation:
        - error
        -   allowKeywords: false
    eol-last:
        - error
        - always
    for-direction: error
    func-call-spacing:
        - error
        - never
    func-style:
        - error
        - expression
    function-paren-newline:
        - error
        - multiline
    key-spacing:
        - error
        -   mode: strict
    import/order:
        - error
    json/*:
        - error
        -   allowComments: true
    node/exports-style: error
    node/no-deprecated-api: error
    node/no-missing-import: error
    node/no-missing-require: error
    node/no-unpublished-bin: error
    node/no-unpublished-import: error
    node/no-unpublished-require: error
    node/process-exit-as-throw: error
    node/shebang: error
