---
env:
    es6: true
    node: true
extends:
    - eslint:recommended
    - plugin:import/errors
    - plugin:import/warnings
    - plugin:json/recommended
    - plugin:node/recommended
    - plugin:yaml/recommended
plugins:
    - import
    - json
    - node
    - unicorn
    - yaml
parserOptions:
    sourceType: module
    ecmaVersion: 2020
rules:
    indent:
        - error
        - 4
    quotes:
        - error
        - double
    semi:
        - error
        - never
    array-bracket-spacing:
        - error
        - always
        -   singleValue: false
            arraysInArrays: false
            objectsInArrays: false
    array-bracket-newline:
        - error
        - consistent
    array-element-newline:
        - error
        - consistent
    arrow-body-style:
        - error
        - as-needed
    arrow-parens:
        - error
        - as-needed
        -   requireForBlockBody: true
    block-spacing: error
    brace-style:
        - error
        - 1tbs
        -   allowSingleLine: true
    comma-dangle:
        - error
        - never
    comma-spacing:
        - error
        -   before: false
            after: true
    comma-style:
        - error
        - last
    computed-property-spacing:
        - error
        - never
        -   enforceForClassMembers: true
    constructor-super: error
    curly:
        - error
        - multi
    default-case: error
    default-case-last: error
    default-param-last:
        - error
    dot-notation:
        - error
        -   allowKeywords: false
    eol-last:
        - error
        - always
    for-direction: error
    func-call-spacing:
        - error
        - never
    func-style:
        - error
        - expression
    function-paren-newline:
        - error
        - multiline
    implicit-arrow-linebreak:
        - error
        - beside
    key-spacing:
        - error
        -   mode: strict
    no-confusing-arrow:
        - error
        -   allowParens: true
    no-process-exit: off
    operator-linebreak: error
    padding-line-between-statements:
        - error
        -   blankLine: always
            prev: "*"
            next: return
        -   blankLine: always
            prev:
                - const
                - let
                - var
            next: "*"
        -   blankLine: any
            prev:
                - const
                - let
                - var
            next:
                - const
                - let
                - var
        -   blankLine: always
            prev: directive
            next: "*"
        -   blankLine: any
            prev: directive
            next: directive
        -   blankLine: always
            prev:
                - case
                - default
            next: "*"
    prefer-arrow-callback:
        - error
        -   allowNamedFunctions: true
    require-await: error
    require-yield: error
    rest-spread-spacing:
        - error
        - never
    import/order: error
    json/*:
        - error
        -   allowComments: true
    node/exports-style: error
    node/no-deprecated-api: error
    node/no-missing-import: error
    node/no-missing-require: error
    node/no-unpublished-bin: error
    node/no-unpublished-import: error
    node/no-unpublished-require: error
    node/process-exit-as-throw: error
    node/shebang: error
    unicorn/better-regex: error
    unicorn/catch-error-name: error
    unicorn/consistent-function-scoping: error
    unicorn/custom-error-definition: off
    unicorn/error-message: error
    unicorn/escape-case: error
    unicorn/expiring-todo-comments: error
    unicorn/explicit-length-check: error
    unicorn/filename-case: error
    unicorn/import-index: error
    unicorn/import-style: error
    unicorn/new-for-builtins: error
    unicorn/no-abusive-eslint-disable: error
    unicorn/no-array-instanceof: error
    unicorn/no-console-spaces: error
    unicorn/no-fn-reference-in-iterator: error
    unicorn/no-for-loop: error
    unicorn/no-hex-escape: error
    unicorn/no-keyword-prefix: off
    no-nested-ternary: off
    unicorn/no-nested-ternary: error
    unicorn/no-new-buffer: error
    unicorn/no-null: error
    unicorn/no-object-as-default-parameter: error
    unicorn/no-reduce: error
    unicorn/no-unreadable-array-destructuring: error
    unicorn/no-unsafe-regex: off
    unicorn/no-unused-properties: off
    unicorn/no-useless-undefined: error
    unicorn/no-zero-fractions: error
    unicorn/number-literal-case: error
    unicorn/prefer-add-event-listener: error
    unicorn/prefer-array-find: error
    unicorn/prefer-dataset: error
    unicorn/prefer-event-key: error
    unicorn/prefer-flat-map: error
    unicorn/prefer-includes: error
    unicorn/prefer-modern-dom-apis: error
    unicorn/prefer-negative-index: error
    unicorn/prefer-node-append: error
    unicorn/prefer-node-remove: error
    unicorn/prefer-number-properties: error
    unicorn/prefer-optional-catch-binding: error
    unicorn/prefer-query-selector: error
    unicorn/prefer-reflect-apply: error
    unicorn/prefer-replace-all: off
    unicorn/prefer-set-has: error
    unicorn/prefer-spread: error
    unicorn/prefer-starts-ends-with: error
    unicorn/prefer-string-slice: error
    unicorn/prefer-ternary: off
    unicorn/prefer-text-content: error
    unicorn/prefer-trim-start-end: error
    unicorn/prefer-type-error: error
    unicorn/prevent-abbreviations: error
    unicorn/string-content: off
    unicorn/throw-new-error: error
